/**
 * src/utils/uiStrings.js — Kiddsy
 * ─────────────────────────────────────────────────────────────────────────
 * Single source of truth for all UI strings across every page.
 * The default language is ALWAYS English ("en").
 *
 * Usage:
 *   import { t } from "../utils/uiStrings.js";
 *   t("hero.cta", lang)          // → "Let's Play!" or localised version
 *   t("hero.cta", "fr")          // → "On joue !"
 *   t("missing.key", lang)       // → falls back silently to English
 *
 * To add a new string:
 *   1. Add the English value under the right namespace key.
 *   2. Add translations for as many languages as available.
 *   3. Missing languages auto-fall back to English — never crashes.
 * ─────────────────────────────────────────────────────────────────────────
 */

const UI = {

  // ════════════════════════════════════════════════════════════════════════
  // HERO SCREEN
  // ════════════════════════════════════════════════════════════════════════
  "hero.headline1":  { en:"Welcome to your",       es:"Bienvenido a tu",         fr:"Bienvenue dans ton",      ar:"مرحباً بك في",          de:"Willkommen in deinem",    pt:"Bem-vindo à tua",         it:"Benvenuto nella tua",     zh:"欢迎来到你的",     ja:"ようこそ",           ko:"어서오세요",       ru:"Добро пожаловать в твой", hi:"अपने में आपका स्वागत है", tr:"Maceranda hoş geldin",    nl:"Welkom in jouw",          pl:"Witaj w swojej",          sv:"Välkommen till ditt" },
  "hero.headline2":  { en:"bilingual adventure!",  es:"¡aventura bilingüe!",     fr:"aventure bilingue !",     ar:"مغامرة ثنائية اللغة!",  de:"zweisprachigen Abenteuer!",pt:"aventura bilingue!",      it:"avventura bilingue!",     zh:"双语冒险！",        ja:"バイリンガルの冒険へ！",  ko:"이중 언어 모험으로!",   ru:"двуязычное приключение!", hi:"द्विभाषी साहसिक काम!",   tr:"iki dilli maceranda!",    nl:"tweetalig avontuur!",     pl:"przygodę dwujęzyczną!",  sv:"tvåspråkiga äventyr!" },
  "hero.subtitle":   { en:"Magical bilingual stories and games in 16 global languages", es:"Cuentos bilingües mágicos y juegos en 16 idiomas", fr:"Histoires bilingues magiques et jeux en 16 langues", ar:"قصص وألعاب ثنائية اللغة في 16 لغة عالمية", de:"Magische zweisprachige Geschichten und Spiele in 16 Sprachen", pt:"Histórias bilingues mágicas e jogos em 16 idiomas", it:"Storie bilingui magiche e giochi in 16 lingue", zh:"16种语言的神奇双语故事和游戏", ja:"16言語の魔法のバイリンガルストーリーとゲーム", ko:"16개 언어로 즐기는 마법의 이중 언어 이야기와 게임", ru:"Волшебные двуязычные истории и игры на 16 языках", hi:"16 वैश्विक भाषाओं में जादुई द्विभाषी कहानियाँ और खेल", tr:"16 küresel dilde sihirli iki dilli hikayeler ve oyunlar", nl:"Magische tweetalige verhalen en spellen in 16 talen", pl:"Magiczne dwujęzyczne opowieści i gry w 16 językach", sv:"Magiska tvåspråkiga berättelser och spel på 16 språk" },
  "hero.cta":        { en:"Let's Play!",            es:"¡A jugar!",               fr:"On joue !",               ar:"هيا نلعب!",              de:"Spielen wir!",            pt:"Vamos jogar!",            it:"Giochiamo!",              zh:"开始玩！",          ja:"遊ぼう！",           ko:"놀자!",             ru:"Играем!",                 hi:"खेलते हैं!",              tr:"Oynayalım!",             nl:"Laten we spelen!",        pl:"Grajmy!",                sv:"Vi spelar!" },
  "hero.badge.stories": { en:"Unlimited Stories",  es:"Cuentos ilimitados",      fr:"Histoires illimitées",    ar:"قصص غير محدودة",        de:"Unbegrenzte Geschichten", pt:"Histórias ilimitadas",    it:"Storie illimitate",       zh:"无限故事",          ja:"無限のストーリー",    ko:"무제한 이야기",     ru:"Неограниченные истории",  hi:"असीमित कहानियाँ",         tr:"Sınırsız hikayeler",      nl:"Onbeperkte verhalen",     pl:"Nieograniczone opowieści",sv:"Obegränsade berättelser" },
  "hero.badge.games":   { en:"Fun Games",          es:"Juegos divertidos",       fr:"Jeux amusants",           ar:"ألعاب ممتعة",            de:"Spaßige Spiele",          pt:"Jogos divertidos",        it:"Giochi divertenti",       zh:"趣味游戏",          ja:"楽しいゲーム",       ko:"재미있는 게임",     ru:"Веселые игры",            hi:"मजेदार खेल",              tr:"Eğlenceli oyunlar",       nl:"Leuke spellen",           pl:"Zabawne gry",             sv:"Roliga spel" },
  "hero.badge.langs":   { en:"16 Languages",       es:"16 Idiomas",              fr:"16 Langues",              ar:"16 لغة",                 de:"16 Sprachen",             pt:"16 Idiomas",              it:"16 Lingue",               zh:"16种语言",          ja:"16言語",             ko:"16개 언어",        ru:"16 языков",               hi:"16 भाषाएँ",               tr:"16 Dil",                  nl:"16 Talen",                pl:"16 języków",              sv:"16 Språk" },
  "hero.guest":      { en:"Create an account to save stories to your library • Optional", es:"Crea una cuenta para guardar cuentos • Opcional", fr:"Créez un compte pour sauvegarder vos histoires • Optionnel", ar:"أنشئ حساباً لحفظ القصص • اختياري", de:"Erstelle ein Konto zum Speichern von Geschichten • Optional", pt:"Crie uma conta para guardar histórias • Opcional", it:"Crea un account per salvare le storie • Opzionale", zh:"创建账号以保存故事 · 可选", ja:"アカウントを作成してストーリーを保存 • 任意", ko:"스토리를 저장하려면 계정을 만드세요 • 선택 사항", ru:"Создайте аккаунт для сохранения историй • Необязательно", hi:"कहानियाँ सहेजने के लिए खाता बनाएं • वैकल्पिक", tr:"Hikayeleri kaydetmek için hesap oluşturun • İsteğe bağlı", nl:"Maak een account aan om verhalen op te slaan • Optioneel", pl:"Utwórz konto, aby zapisywać opowieści • Opcjonalne", sv:"Skapa ett konto för att spara berättelser • Valfritt" },

  // ════════════════════════════════════════════════════════════════════════
  // GAMES (shell + SlidingPuzzle + MemoryMatch)
  // ════════════════════════════════════════════════════════════════════════
  "games.title":       { en:"Game Zone",           es:"Zona de Juegos",          fr:"Zone de Jeux",            ar:"منطقة الألعاب",          de:"Spielzone",               pt:"Zona de Jogos",           it:"Area Giochi",             zh:"游戏区",            ja:"ゲームゾーン",       ko:"게임 존",          ru:"Игровая зона",            hi:"गेम ज़ोन",                tr:"Oyun Bölgesi",            nl:"Spelzone",                pl:"Strefa Gier",             sv:"Spelzon" },
  "games.subtitle":    { en:"Fun games that make learning English feel like playtime!", es:"¡Juegos divertidos que hacen que aprender inglés parezca un juego!", fr:"Des jeux amusants qui font que l'apprentissage de l'anglais ressemble à du jeu !", ar:"ألعاب ممتعة تجعل تعلم الإنجليزية يشبه وقت اللعب!", de:"Spaßige Spiele, die das Englischlernen wie Spielen anfühlen lassen!", pt:"Jogos divertidos que fazem a aprendizagem do inglês parecer uma brincadeira!", it:"Giochi divertenti che rendono l'apprendimento dell'inglese come un gioco!", zh:"让学英语变得像玩耍一样有趣的游戏！", ja:"英語学習が遊び時間のように感じられる楽しいゲーム！", ko:"영어 학습이 놀이처럼 느껴지게 하는 재미있는 게임!", ru:"Веселые игры, которые делают изучение английского похожим на игру!", hi:"मजेदार खेल जो अंग्रेजी सीखना खेलने जैसा बनाते हैं!", tr:"İngilizce öğrenmeyi oyun gibi hissettiren eğlenceli oyunlar!", nl:"Leuke spellen waardoor het leren van Engels aanvoelt als spelen!", pl:"Zabawne gry, które sprawiają, że nauka angielskiego przypomina zabawę!", sv:"Roliga spel som gör att lära sig engelska känns som lek!" },
  "games.meta":        { en:"4 categories · 25 icon variants", es:"4 categorías · 25 variantes de iconos", fr:"4 catégories · 25 variantes d'icônes", ar:"4 فئات · 25 نوعاً من الأيقونات", de:"4 Kategorien · 25 Icon-Varianten", pt:"4 categorias · 25 variantes de ícones", it:"4 categorie · 25 varianti di icone", zh:"4个类别 · 25种图标变体", ja:"4カテゴリー · 25アイコンバリエーション", ko:"4개 카테고리 · 25개 아이콘 변형", ru:"4 категории · 25 вариантов иконок", hi:"4 श्रेणियाँ · 25 आइकन वेरिएंट", tr:"4 kategori · 25 ikon çeşidi", nl:"4 categorieën · 25 iconvarianten", pl:"4 kategorie · 25 wariantów ikon", sv:"4 kategorier · 25 ikonvarianter" },
  "games.tab.puzzle":  { en:"Tile Puzzle",         es:"Puzzle de Piezas",        fr:"Puzzle de Tuiles",        ar:"لغز البلاط",             de:"Kachel-Puzzle",           pt:"Puzzle de Peças",         it:"Puzzle a Tessere",        zh:"拼图",              ja:"タイルパズル",       ko:"타일 퍼즐",        ru:"Пазл из плиток",          hi:"टाइल पज़ल",               tr:"Döşeme Yapbozu",          nl:"Tegellegpuzzel",          pl:"Puzzle z kafelków",       sv:"Pusselplattor" },
  "games.tab.memory":  { en:"Memory Match",        es:"Memoria",                 fr:"Jeu de Mémoire",          ar:"لعبة الذاكرة",           de:"Memory-Spiel",            pt:"Jogo da Memória",         it:"Gioco della Memoria",     zh:"记忆配对",          ja:"神経衰弱",           ko:"메모리 매치",      ru:"Игра на память",          hi:"मेमोरी मैच",              tr:"Hafıza Oyunu",            nl:"Geheugenspel",            pl:"Gra pamięciowa",          sv:"Memory" },
  "games.puzzle.solved": { en:"Solved!",           es:"¡Resuelto!",              fr:"Résolu !",                ar:"تم الحل!",               de:"Gelöst!",                 pt:"Resolvido!",              it:"Risolto!",                zh:"解开了！",          ja:"解けた！",           ko:"풀었어요!",        ru:"Решено!",                 hi:"हल हो गया!",             tr:"Çözüldü!",               nl:"Opgelost!",               pl:"Rozwiązano!",             sv:"Löst!" },
  "games.puzzle.new":  { en:"New puzzle",          es:"Nuevo puzzle",            fr:"Nouveau puzzle",          ar:"لغز جديد",              de:"Neues Puzzle",            pt:"Novo puzzle",             it:"Nuovo puzzle",            zh:"新拼图",            ja:"新しいパズル",       ko:"새 퍼즐",          ru:"Новый пазл",              hi:"नई पहेली",               tr:"Yeni yapboz",             nl:"Nieuw puzzel",            pl:"Nowa układanka",          sv:"Nytt pussel" },
  "games.puzzle.target": { en:"Target order",      es:"Orden objetivo",          fr:"Ordre cible",             ar:"الترتيب المطلوب",        de:"Zielreihenfolge",         pt:"Ordem alvo",              it:"Ordine obiettivo",        zh:"目标顺序",          ja:"目標の順序",         ko:"목표 순서",        ru:"Целевой порядок",         hi:"लक्ष्य क्रम",            tr:"Hedef sıra",              nl:"Doelvolgorde",            pl:"Docelowa kolejność",      sv:"Målordning" },
  "games.memory.win":  { en:"You win!",            es:"¡Ganaste!",               fr:"Tu gagnes !",             ar:"لقد فزت!",              de:"Du gewinnst!",            pt:"Ganhou!",                 it:"Hai vinto!",              zh:"你赢了！",          ja:"あなたの勝ち！",     ko:"이겼어요!",        ru:"Ты выиграл!",             hi:"आप जीत गए!",             tr:"Kazandın!",               nl:"Je wint!",                pl:"Wygrałeś!",               sv:"Du vinner!" },
  "games.memory.new":  { en:"New game",            es:"Nuevo juego",             fr:"Nouvelle partie",         ar:"لعبة جديدة",            de:"Neues Spiel",             pt:"Novo jogo",               it:"Nuova partita",           zh:"新游戏",            ja:"新しいゲーム",       ko:"새 게임",          ru:"Новая игра",              hi:"नया खेल",                tr:"Yeni oyun",               nl:"Nieuw spel",              pl:"Nowa gra",                sv:"Nytt spel" },
  "games.memory.tried":{ en:"pairs tried",         es:"pares intentados",        fr:"paires essayées",         ar:"أزواج جربتها",          de:"Paare versucht",          pt:"pares tentados",          it:"coppie tentate",          zh:"尝试对数",          ja:"試した組",           ko:"시도한 쌍",        ru:"пар попыток",             hi:"जोड़े आजमाए",            tr:"çift denendi",            nl:"paren geprobeerd",        pl:"prób par",                sv:"par försökt" },
  "games.memory.found":{ en:"found",               es:"encontrados",             fr:"trouvées",                ar:"وجدتها",                de:"gefunden",                pt:"encontrados",             it:"trovate",                 zh:"已找到",            ja:"見つけた",           ko:"찾음",             ru:"найдено",                 hi:"मिले",                   tr:"bulundu",                 nl:"gevonden",                pl:"znaleziono",              sv:"hittade" },

  // ════════════════════════════════════════════════════════════════════════
  // WORD SEARCH
  // ════════════════════════════════════════════════════════════════════════
  "ws.title":          { en:"Word Hunt",            es:"Caza Palabras",           fr:"Chasse aux Mots",         ar:"صيد الكلمات",            de:"Wortjagd",                pt:"Caça Palavras",           it:"Caccia alle Parole",      zh:"单词猎手",          ja:"ワードハント",       ko:"단어 사냥",        ru:"Охота за словами",        hi:"शब्द शिकार",             tr:"Kelime Avı",              nl:"Woorden Zoeken",          pl:"Polowanie na Słowa",      sv:"Ordjakt" },
  "ws.subtitle":       { en:"Find all the hidden English words!", es:"¡Encuentra todas las palabras en inglés!", fr:"Trouve tous les mots anglais cachés !", ar:"ابحث عن جميع الكلمات الإنجليزية المخفية!", de:"Finde alle versteckten englischen Wörter!", pt:"Encontra todas as palavras em inglês!", it:"Trova tutte le parole inglesi nascoste!", zh:"找出所有隐藏的英文单词！", ja:"隠された英単語をすべて見つけよう！", ko:"숨겨진 모든 영어 단어를 찾아보세요!", ru:"Найди все скрытые английские слова!", hi:"सभी छुपे अंग्रेज़ी शब्द ढूंढो!", tr:"Gizlenmiş tüm İngilizce kelimeleri bul!", nl:"Vind alle verstopte Engelse woorden!", pl:"Znajdź wszystkie ukryte angielskie słowa!", sv:"Hitta alla gömda engelska ord!" },
  "ws.newPuzzle":      { en:"New puzzle",           es:"Nuevo puzzle",            fr:"Nouveau puzzle",          ar:"لعبة جديدة",            de:"Neues Rätsel",            pt:"Novo puzzle",             it:"Nuovo puzzle",            zh:"新游戏",            ja:"新しいパズル",       ko:"새 게임",          ru:"Новая игра",              hi:"नई पहेली",               tr:"Yeni bulmaca",            nl:"Nieuw puzzel",            pl:"Nowa układanka",          sv:"Nytt pussel" },
  "ws.findWords":      { en:"Find these words",     es:"Encuentra estas palabras", fr:"Trouve ces mots",        ar:"ابحث عن هذه الكلمات",   de:"Finde diese Wörter",      pt:"Encontre estas palavras", it:"Trova queste parole",     zh:"找找这些单词",      ja:"これらの言葉を探して",ko:"이 단어들을 찾아보세요", ru:"Найди эти слова",         hi:"ये शब्द खोजें",          tr:"Bu kelimeleri bul",       nl:"Vind deze woorden",       pl:"Znajdź te słowa",         sv:"Hitta dessa ord" },
  "ws.wellDone":       { en:"Well done! You found all the words!", es:"¡Muy bien! ¡Encontraste todas las palabras!", fr:"Bravo ! Tu as trouvé tous les mots !", ar:"أحسنت! لقد وجدت جميع الكلمات!", de:"Super! Du hast alle Wörter gefunden!", pt:"Muito bem! Encontraste todas as palavras!", it:"Bravissimo! Hai trovato tutte le parole!", zh:"太棒了！你找到了所有单词！", ja:"よくできました！全部の言葉を見つけたよ！", ko:"잘했어요! 모든 단어를 찾았어요!", ru:"Молодец! Ты нашёл все слова!", hi:"शाबाश! तुमने सभी शब्द खोज लिए!", tr:"Harika! Tüm kelimeleri buldun!", nl:"Goed gedaan! Je hebt alle woorden gevonden!", pl:"Świetnie! Znalazłeś wszystkie słowa!", sv:"Bra jobbat! Du hittade alla orden!" },
  "ws.howToPlay":      { en:"How to play",          es:"Cómo jugar",              fr:"Comment jouer",           ar:"كيف تلعب",              de:"So spielst du",           pt:"Como jogar",              it:"Come si gioca",           zh:"如何游戏",          ja:"遊び方",             ko:"게임 방법",        ru:"Как играть",              hi:"कैसे खेलें",             tr:"Nasıl oynanır",           nl:"Hoe te spelen",           pl:"Jak grać",                sv:"Hur man spelar" },
  "ws.instructions":   { en:"Click and drag across letters to select a word. Words can go in any direction: horizontal, vertical, or diagonal!", es:"Haz clic y arrastra por las letras para seleccionar una palabra. Las palabras pueden ir en cualquier dirección: horizontal, vertical o diagonal.", fr:"Clique et glisse sur les lettres pour sélectionner un mot. Les mots peuvent aller dans n'importe quelle direction : horizontal, vertical ou diagonal !", ar:"انقر واسحب عبر الحروف لتحديد كلمة. يمكن أن تسير الكلمات في أي اتجاه: أفقي أو رأسي أو قطري!", de:"Klicke und ziehe über die Buchstaben, um ein Wort auszuwählen. Wörter können in jede Richtung gehen: horizontal, vertikal oder diagonal!", pt:"Clica e arrasta pelas letras para selecionar uma palavra. As palavras podem ir em qualquer direção: horizontal, vertical ou diagonal!", it:"Clicca e trascina sulle lettere per selezionare una parola. Le parole possono andare in qualsiasi direzione: orizzontale, verticale o diagonale!", zh:"点击并拖拽字母来选择一个单词。单词可以朝任何方向：水平、垂直或对角线！", ja:"文字をクリックしてドラッグして単語を選択します。単語は水平・垂直・斜めのどの方向にも向かいます！", ko:"글자를 클릭하고 드래그하여 단어를 선택하세요. 단어는 가로, 세로, 대각선 어떤 방향으로도 갈 수 있어요!", ru:"Кликни и проведи по буквам, чтобы выделить слово. Слова могут идти в любом направлении: горизонтальном, вертикальном или диагональном!", hi:"शब्द चुनने के लिए अक्षरों पर क्लिक करें और खींचें। शब्द किसी भी दिशा में हो सकते हैं: क्षैतिज, ऊर्ध्वाधर या विकर्ण!", tr:"Bir kelime seçmek için harflerin üzerine tıkla ve sürükle. Kelimeler yatay, dikey veya çapraz herhangi bir yönde gidebilir!", nl:"Klik en sleep over de letters om een woord te selecteren. Woorden kunnen in elke richting gaan: horizontaal, verticaal of diagonaal!", pl:"Kliknij i przeciągnij po literach, aby wybrać słowo. Słowa mogą iść w dowolnym kierunku: poziomo, pionowo lub po przekątnej!", sv:"Klicka och dra över bokstäverna för att välja ett ord. Ord kan gå i vilken riktning som helst: horisontellt, vertikalt eller diagonalt!" },

  // ════════════════════════════════════════════════════════════════════════
  // STORY READER
  // ════════════════════════════════════════════════════════════════════════
  "reader.back":            { en:"Library",         es:"Biblioteca",              fr:"Bibliothèque",            ar:"المكتبة",               de:"Bibliothek",              pt:"Biblioteca",              it:"Libreria",                zh:"图书馆",            ja:"ライブラリ",         ko:"도서관",           ru:"Библиотека",              hi:"पुस्तकालय",              tr:"Kütüphane",               nl:"Bibliotheek",             pl:"Biblioteka",              sv:"Bibliotek" },
  "reader.page":            { en:"Page",            es:"Página",                  fr:"Page",                    ar:"صفحة",                  de:"Seite",                   pt:"Página",                  it:"Pagina",                  zh:"第",               ja:"ページ",             ko:"페이지",           ru:"Страница",                hi:"पृष्ठ",                  tr:"Sayfa",                   nl:"Pagina",                  pl:"Strona",                  sv:"Sida" },
  "reader.previous":        { en:"Previous",        es:"Anterior",                fr:"Précédent",               ar:"السابق",                de:"Zurück",                  pt:"Anterior",                it:"Precedente",              zh:"上一页",            ja:"前へ",               ko:"이전",             ru:"Назад",                   hi:"पिछला",                  tr:"Önceki",                  nl:"Vorige",                  pl:"Poprzedni",               sv:"Föregående" },
  "reader.next":            { en:"Next",            es:"Siguiente",               fr:"Suivant",                 ar:"التالي",                de:"Weiter",                  pt:"Próximo",                 it:"Successivo",              zh:"下一页",            ja:"次へ",               ko:"다음",             ru:"Вперёд",                  hi:"अगला",                   tr:"Sonraki",                 nl:"Volgende",                pl:"Następny",                sv:"Nästa" },
  "reader.theEnd":          { en:"The End ✨",       es:"Fin ✨",                  fr:"Fin ✨",                   ar:"النهاية ✨",             de:"Ende ✨",                  pt:"Fim ✨",                   it:"Fine ✨",                  zh:"结局 ✨",            ja:"おわり ✨",           ko:"끝 ✨",            ru:"Конец ✨",                 hi:"समाप्त ✨",               tr:"Son ✨",                   nl:"Einde ✨",                 pl:"Koniec ✨",                sv:"Slut ✨" },
  "reader.readNow":         { en:"Read now",        es:"Leer ahora",              fr:"Lire maintenant",         ar:"اقرأ الآن",             de:"Jetzt lesen",             pt:"Ler agora",               it:"Leggi ora",               zh:"立即阅读",          ja:"今すぐ読む",         ko:"지금 읽기",        ru:"Читать сейчас",           hi:"अभी पढ़ें",              tr:"Şimdi oku",               nl:"Nu lezen",                pl:"Czytaj teraz",            sv:"Läs nu" },
  "reader.pages":           { en:"pages",           es:"páginas",                 fr:"pages",                   ar:"صفحات",                 de:"Seiten",                  pt:"páginas",                 it:"pagine",                  zh:"页",               ja:"ページ",             ko:"페이지",           ru:"страниц",                 hi:"पृष्ठ",                  tr:"sayfa",                   nl:"pagina's",                pl:"stron",                   sv:"sidor" },
  "reader.listen":          { en:"Listen",          es:"Escuchar",                fr:"Écouter",                 ar:"استمع",                 de:"Anhören",                 pt:"Ouvir",                   it:"Ascolta",                 zh:"听一听",            ja:"聴く",               ko:"듣기",             ru:"Слушать",                 hi:"सुनें",                  tr:"Dinle",                   nl:"Luisteren",               pl:"Słuchaj",                 sv:"Lyssna" },
  "reader.playAgain":       { en:"Play again",      es:"Reproducir de nuevo",     fr:"Rejouer",                 ar:"اعد التشغيل",           de:"Nochmals abspielen",      pt:"Reproduzir novamente",    it:"Riproduci ancora",        zh:"再次播放",          ja:"もう一度再生",       ko:"다시 재생",        ru:"Воспроизвести снова",     hi:"फिर से सुनें",           tr:"Tekrar oynat",            nl:"Opnieuw afspelen",        pl:"Odtwórz ponownie",        sv:"Spela igen" },
  "reader.loading":         { en:"Loading…",        es:"Cargando…",               fr:"Chargement…",             ar:"جار التحميل…",          de:"Lädt…",                   pt:"A carregar…",             it:"Caricamento…",            zh:"加载中…",           ja:"読み込み中…",        ko:"로딩 중…",         ru:"Загрузка…",               hi:"लोड हो रहा है…",         tr:"Yükleniyor…",             nl:"Laden…",                  pl:"Ładowanie…",              sv:"Laddar…" },
  "reader.noTranslation":   { en:"Translation not available", es:"Traducción no disponible", fr:"Traduction non disponible", ar:"الترجمة غير متاحة",  de:"Übersetzung nicht verfügbar", pt:"Tradução não disponível", it:"Traduzione non disponibile", zh:"翻译不可用",      ja:"翻訳がありません",   ko:"번역 없음",        ru:"Перевод недоступен",      hi:"अनुवाद उपलब्ध नहीं",    tr:"Çeviri mevcut değil",     nl:"Vertaling niet beschikbaar", pl:"Tłumaczenie niedostępne", sv:"Översättning saknas" },
  "reader.comingSoon":      { en:"Coming soon",     es:"Próximamente",            fr:"Bientôt disponible",      ar:"قريباً",                de:"Demnächst",               pt:"Em breve",                it:"Presto disponibile",      zh:"即将推出",          ja:"近日公開",           ko:"곧 출시",          ru:"Скоро",                   hi:"जल्द आ रहा है",          tr:"Yakında",                 nl:"Binnenkort",              pl:"Wkrótce",                 sv:"Kommer snart" },
  "reader.browserTTS":      { en:"Browser TTS",     es:"Voz del navegador",       fr:"Voix du navigateur",      ar:"صوت المتصفح",           de:"Browser-Stimme",          pt:"Voz do navegador",        it:"Voce del browser",        zh:"浏览器语音",        ja:"ブラウザ音声",       ko:"브라우저 TTS",     ru:"Голос браузера",          hi:"ब्राउज़र TTS",           tr:"Tarayıcı sesi",           nl:"Browser TTS",             pl:"TTS przeglądarki",        sv:"Webbläsaren TTS" },
  "reader.demoLabel":       { en:"Demo Stories — Free", es:"Cuentos Demo — Gratis", fr:"Histoires Démo — Gratuites", ar:"قصص تجريبية — مجانية", de:"Demo-Geschichten — Kostenlos", pt:"Histórias Demo — Grátis", it:"Storie Demo — Gratis", zh:"演示故事 — 免费",   ja:"デモストーリー — 無料", ko:"데모 이야기 — 무료", ru:"Демо-истории — Бесплатно", hi:"डेमो कहानियाँ — मुफ़्त", tr:"Demo Hikayeler — Ücretsiz", nl:"Demoverhalen — Gratis",  pl:"Opowieści Demo — Bezpłatne", sv:"Demosagor — Gratis" },

  // ════════════════════════════════════════════════════════════════════════
  // STORY GENERATOR
  // ════════════════════════════════════════════════════════════════════════
  "gen.langHint":      { en:"Story will be generated in English + {lang}", es:"La historia se generará en inglés + {lang}", fr:"L'histoire sera générée en anglais + {lang}", ar:"ستُنشأ القصة بالإنجليزية + {lang}", de:"Geschichte wird auf Englisch + {lang} generiert", pt:"A história será gerada em inglês + {lang}", it:"La storia sarà generata in inglese + {lang}", zh:"故事将以英语 + {lang} 生成", ja:"ストーリーは英語＋{lang}で生成されます", ko:"이야기는 영어 + {lang}로 생성됩니다", ru:"История будет создана на английском + {lang}", hi:"कहानी अंग्रेजी + {lang} में तैयार की जाएगी", tr:"Hikaye İngilizce + {lang} olarak oluşturulacak", nl:"Verhaal wordt gegenereerd in Engels + {lang}", pl:"Historia zostanie wygenerowana po angielsku + {lang}", sv:"Berättelsen skapas på engelska + {lang}" },
  "gen.translationLang": { en:"Translation language", es:"Idioma de traducción", fr:"Langue de traduction", ar:"لغة الترجمة", de:"Übersetzungssprache", pt:"Idioma de tradução", it:"Lingua di traduzione", zh:"翻译语言", ja:"翻訳言語", ko:"번역 언어", ru:"Язык перевода", hi:"अनुवाद भाषा", tr:"Çeviri dili", nl:"Vertaaltaal", pl:"Język tłumaczenia", sv:"Översättningsspråk" },
};

/**
 * t(key, lang) — translate a UI string key to the given language.
 * Falls back to English if the translation is missing.
 * Supports {lang} placeholder replacement.
 *
 * @param {string} key  - dot-notation key, e.g. "hero.cta"
 * @param {string} lang - BCP-47 2-letter code, e.g. "es"
 * @param {object} [vars] - optional { lang: "Español" } for placeholder substitution
 * @returns {string}
 */
export function t(key, lang = "en", vars = {}) {
  const entry = UI[key];
  if (!entry) {
    if (process.env.NODE_ENV === "development") {
      console.warn(`[uiStrings] Missing key: "${key}"`);
    }
    return key;
  }
  let str = entry[lang] ?? entry["en"] ?? key;
  // Replace {placeholder} variables
  Object.entries(vars).forEach(([k, v]) => {
    str = str.replace(`{${k}}`, v);
  });
  return str;
}

export default UI;
